// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inrivbbifhraowqlqzsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlucml2YmJpZmhyYW93cWxxenNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMjExMjcsImV4cCI6MjA3NzU5NzEyN30.aBUOaK5bQuVATJ7Ig_ZyqihgDpx1tiPgRvakRE1PgIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});